### ISSUE TITLE
can you give a json that i can use you plugins

### ISSUE THREAD

**Issue by Rigaln** [electr0sheep/ItemVendorLocation#1]
can you give a json that i can use you plugins

**Comment by electr0sheep** [comment]
Sorry, but I don't understand. Would you mind restating your question?

**Comment by Akurosia** [comment]
i think he wants a repo.json to find all your plugins in the dalamud list

**Comment by electr0sheep** [comment]
Oh, if you are simply looking for access to the plugin, I believe there is an easier way.

Simply go to Dalamud Settings > Experimental > Get plugin testing builds

You should then see this plugin, as well as all the other plugins that are in the "testing" phase.

**Comment by electr0sheep** [comment]
I'm going to assume that worked for you and close this out. Feel free to comment again if you still need help.
