### ISSUE TITLE
Vendor Location gets added to every context menu.

### ISSUE THREAD

**Issue by Nikslg** [electr0sheep/ItemVendorLocation#13]
I have a habbit of clicking on player names in chat, and this is when I noticed that [Vendor Location] Option actually gets added to windows that aren't related to Items. For example if you right click on player name in chat to whisper them.
![image](https://user-images.githubusercontent.com/15956980/160628905-9965ef64-be88-4445-840f-e4be04b29f9b.png)

**Comment by electr0sheep** [comment]
I've noticed the same thing, and I think I fixed at some point. I need to do another release.

**Comment by electr0sheep** [comment]
Yeah, I found this issue as well with https://github.com/electr0sheep/ItemVendorLocation/issues/8.

I'm dong a release now which should resolve this.

**Comment by electr0sheep** [comment]
I'm going to pre-emptively close this out, assuming that the [0.0.0.3 update](https://github.com/goatcorp/DalamudPlugins/pull/2205) will fix it

**Comment by electr0sheep** [comment]
@Nikslg the update was merged. Let me know if that fixes it for you.

**Comment by Nikslg** [comment]
I think it was fixed.
