### ISSUE TITLE
Key down modifier to show all results

### ISSUE THREAD

**Issue by drejjmit** [electr0sheep/ItemVendorLocation#15]
Love the Plugin, but i have one feature request that i think would make it even better:

Would it be possible to have a Key down option to show all vendors?

For example: If i hold Shift while pressing "Vendor location" it opens the Dalamud popup window with all results, even if "Show only one vendor" option is active.

**Comment by electr0sheep** [comment]
@drejjmit Did you find the only one vendor option useful? I have actually removed it entirely cause I didn't think it was good.

**Comment by drejjmit** [comment]
I tried without the "Show only one vendor" option turned on but switched back to having it show the results without the popup.
Maybe you could have it work like "one vendor" if only one vendor is found?
![image](https://user-images.githubusercontent.com/15526476/168010407-d16ef0cd-7deb-49cc-b124-5ab47d75ef64.png)
This is such a useless popup result for example, since there's only one vendor anyways

**Comment by drejjmit** [comment]
``It can simply find the first vendor and link the coordinates in the in-game chat (I will most likely be deprecating this)``
![image](https://user-images.githubusercontent.com/15526476/187314530-c3a71943-88a6-4413-b161-7758def07643.png)

I miss the option already 😭
I will probably stay on v0.0.0.4

**Comment by drejjmit** [comment]
I just think it's clean with the small note in chat without a popup. And if it says "Storm Quartermaster" it's not that hard to figure out that "Serpent Quartermaster" will sell it as well. Never encountered an instance where i couldn't figure out where to go with just 1 result.
``¯\_(ツ)_/¯``

**Comment by electr0sheep** [comment]
I will re-add this functionality in a future release since people found it useful.

**Comment by electr0sheep** [comment]
I've re-added the single vendor option. The key down modifier is an interesting idea.

**Comment by electr0sheep** [comment]
I've also added a key modifier to display results via the unselected method (pending a new release I'm working on)
