### ISSUE TITLE
Multiple context menu entries

### ISSUE THREAD

**Issue by electr0sheep** [electr0sheep/ItemVendorLocation#16]
Something must have changed, because I'm seeing multiple context menu entries now

**Comment by Aireil** [comment]
Context menus are cursed. It sometimes does not appear in the material list of the crafting window either.
I'm pretty sure it's an issue with common's implementation, as the code hasn't been updated in a while.

There were plans to add them to Dalamud for 6.2, but it wouldn't change much, hopefully someone is bored enough to implement them properly in Dalamud one day.

**Comment by electr0sheep** [comment]
I think this was caused by having multiple of the same plugin loaded at once (I think the "testing" version, as well as potentially 2 "dev" ones)
