### ISSUE TITLE
Wolf Marks not supported?

### ISSUE THREAD

**Issue by Aireil** [electr0sheep/ItemVendorLocation#18]
Hey, not sure if intended, but it doesn't seem to find vendors for Wolf Marks items. I was looking at [Makai Fists](https://garlandtools.org/db/#item/16068) that are sold for 4000 Wolf Marks.
Thanks for the plugin, it's neat!

**Comment by electr0sheep** [comment]
This will be addressed in the next release. I was for some reason only showing gil vendors, if gil vendors existed.
