### ISSUE TITLE
Vendor Location doesn't show

### ISSUE THREAD

**Issue by I-Am-Caprico** [electr0sheep/ItemVendorLocation#20]
The vendor Location only shows "No Location" on all items. I have just freshly installed this plugin for the first time if that matters.

**Comment by drejjmit** [comment]
Same for me
![image](https://user-images.githubusercontent.com/15526476/187314231-ea61d67f-a75a-49af-b276-adecb20e5d5b.png)

**Comment by kevinkickback** [comment]
I also have this problem.

**Comment by electr0sheep** [comment]
Oops what a silly oversight on my part for the 1.0.0.0 release. I'm looking into it now and hopefully the fix is fairly simple.

**Comment by electr0sheep** [comment]
I have a fix for it, just need to get it deployed. Sorry guys!

**Comment by electr0sheep** [comment]
Just waiting on approval https://github.com/goatcorp/DalamudPluginsD17/pull/319

**Comment by electr0sheep** [comment]
Okay I think the 1.0.0.1 release should be live now. Can someone confirm that the locations are working again, then I'll close the card?

**Comment by I-Am-Caprico** [comment]
Thanks for the quick fix, it works now. :)
