### ISSUE TITLE
DalamudApiLevel not needed anymore

### ISSUE THREAD

**Issue by Diyagi** [electr0sheep/ItemVendorLocation#22]
After the net6 updated, the `DalamudApiLevel` is dictated by `DalamudPackager`, so all you need to do is update `DalamudPackager`.
If you do specify an `DalamudApiLevel` in the json, it will override the API Level from `DalamudPackager`.

**Comment by electr0sheep** [comment]
Removed DalamudApiLevel with 9aa833d23c6ed9c72122c270b61591be68c99ffa
