### ISSUE TITLE
Hotkey

### ISSUE THREAD

**Issue by Kumicoo** [electr0sheep/ItemVendorLocation#23]
Set up a hotkey for Vendor Location (Like CTRL+V?) so it can be used with Chat2 as well. When linking an item in Chat2, it doesnt have any plugin options... Gatherbuddy "Gather" also doesnt work with chat2.

**Comment by electr0sheep** [comment]
I've never used or heard of chat2. After installing it, I can see what you mean. I'll have to investigate at some point.

**Comment by Nukoooo** [comment]
Added chat2 support, sorry for taking so long
