### ISSUE TITLE
Have to right click the item multiple times in Crafting Window to get "Vendor Location" to appear in the menu

### ISSUE THREAD

**Issue by FakeCirka** [electr0sheep/ItemVendorLocation#24]
So when I use the search option in crafting to find the item "Amateur's Fishing Rod", and select it, under the materials section of the craft when I right click any of the 3 items (Ash Lumber, Ash Branch, or Bronze Ingot), it seems completely random if Vendor Location will appear or not. Sometimes I have to close the right click menu down and right click again up to 5 or 6 times before the Vendor Location option appears. Sometimes its there on the first right click, sometimes the 5th, sometimes the third, sometimes it appears 3 times in a row. Just seems completely random on if it will appear or not.

**Comment by electr0sheep** [comment]
I just looked at this and wasn't able to reproduce. Can anyone experiencing this issue confirm if the bug still exists?

**Comment by Rueby** [comment]
Sounds abit similar to [Issue #43 ](https://github.com/electr0sheep/ItemVendorLocation/issues/43)? But I haven't been able to replicate that in the crafting menu.

I even tried repeatedly right clicking to see if it'd glitch out somehow but it is appearing all the time for both crafting materials and the item itself.

**Comment by FakeCirka** [comment]
Have not played in a long while, but checked today and it seems this is no longer happening, so it seems to be fixed. It looks like it was the same issue as the one @Rueby linked.
