### ISSUE TITLE
Command Option

### ISSUE THREAD

**Issue by pellux-network** [electr0sheep/ItemVendorLocation#25]
The current iteration of the plugin requires you to actually have the item (or search in the marketboard) to get the right-click contextual menu. It would be ideal if there was also a command (say "/vendor [item]) so you can search any item, any time.

**Comment by electr0sheep** [comment]
Sorry for the slow response. I'm not sure how I feel about adding item search capabilities. There is an item search plugin you can use to search for items, and link the items to chat, which then you can use this plugin to find the vendor location.

**Comment by electr0sheep** [comment]
I've actually added this. You can use the command /xlvendor [item] to search for items now
