### ISSUE TITLE
[Question] Multiple language support

### ISSUE THREAD

**Issue by github-1348A55** [electr0sheep/ItemVendorLocation#27]
I tried to use it in the JP version FFXIV.
But nothing happens when I select the context menu.
garlandtools.org supports FR/DE/JA item names, although you need to switch..
Will it be possible to respond in Japanese in the future?

**Comment by SeleneBathory** [comment]
Same for French, nothing happens with the context menu. I'd like to have a multiple language support.

**Comment by electr0sheep** [comment]
I think I inadvertently may have solved this. I was looking up the garland tools id, even though it was the same as the in-game ID. It seems to be working for me in the Japanese client at least.

**Comment by electr0sheep** [comment]
Functionality should work with ea27ac3d766d3ebd583340dd9f2bd352b68ddc0d
I tried to further localization with 8a5fdc8e6a30cec51ec421273b6ae2f440fce58c
I only understand a little Japanese, and no French or German, so if you see this and think the localization could be better, please open up an issue, or let me know somehow!

**Comment by github-1348A55** [comment]
Thank you very much.
I did not play for a few days, so I could not check it right away.
However, I just tried a few items and it works in a Japanese environment.
I am glad I don't have to open a browser anymore. 😆
