### ISSUE TITLE
Flags placed are right, locations in chat wrong

### ISSUE THREAD

**Issue by rrbailey89** [electr0sheep/ItemVendorLocation#3]
Please see the attached screenshot for an example:

![image](https://user-images.githubusercontent.com/6540217/150699752-5dcdc49e-fc7a-47e7-a313-87b9f04bef5d.png)

Weirdly enough, although the location name for that flag is very wrong, the flag is in the correct spot and on the correct map.

**Comment by electr0sheep** [comment]
Oh weird. I'll have to take a look, thanks for letting me know!

**Comment by electr0sheep** [comment]
I couldn't find a super good way to deal with location data, so I manually entered in a bunch of numbers. In this case, I typo'd the Kugane location.

Should be fixed with this commit
bf620cc853f849f30fb1f7bd47c054da54b65055
