### ISSUE TITLE
[Bug] Tribal Vendors Problem

### ISSUE THREAD

**Issue by github-1348A55** [electr0sheep/ItemVendorLocation#33]
Thank you for your recent support of other languages.
I will report what I noticed after using.

This is a partial excerpt.
Sylphic Vendor
😁Undyed Linen "East Shroud (22.4 ,26.4)" 411 Gil
😱Undyed Linen "East Shroud (22.4 ,26.4)" 1 Sylphic Goldleaf

Sahagin Vendor
😁Night Milk "Western La Noscea (17.0 ,22.5)" 84 Gil
😱Night Milk "Western La Noscea (17.0 ,22.5)" 1 Rainbowtide Psashp

Vath Stickpeddler
😁Mythrite Nugget "The Dravanian Forelands (23.7 ,19.1)" 2376 Gil
😱Mythrite Nugget "The Dravanian Forelands (23.7 ,19.1)" 1 Black Copper Gil

Luna Vanu
😁Birch Sap "The Sea of Clouds (7.1 ,14.3)" 468 Gil
😱Birch Sap "The Sea of Clouds (7.1 ,14.3)" 1 Vanu Whitebone

If there is a sale of the same item with gil and tribal money,
Tribal money products do not have map and flag responses.
In addition, maps and flags are displayed for items that can only be bought with tribal money.
I hope this problem is resolved.

**Comment by electr0sheep** [comment]
> In addition, maps and flags are displayed for items that can only be bought with tribal money.

Can you clarify this?

**Comment by github-1348A55** [comment]
Mogmul Mogbelly
😁Glass Fiber "The Churning Mists (16.0 ,28.6)" 3 Carved Kupo Nut
This item is available from multiple vendors.
Moogle don't sell this item at a gil, so it will show maps and flags.

Gyosho
😁Stormsap "The Azim Steppe (5.9 ,23.5)" 1 Namazu Koban
This item is for sale with tribal money only.
Maps and flags are fully visible.

**Comment by github-1348A55** [comment]
> > In addition, maps and flags are displayed for items that can only be bought with tribal money.
> Can you clarify this?
Since the text is written using a translation, it may not convey the correct intent.
We apologize if it is difficult to understand.

**Comment by electr0sheep** [comment]
Found out that it was a case of needing each button to have a unique ID for the first issue. I think the second issue is intentional. I do want to show info for all currencies, not just gil.

**Comment by github-1348A55** [comment]
I used to call this problem a tribal vendor, but it actually happens elsewhere.
In vendor locations by Faux Commander and Faux Leaf, there is no map and flag reaction if Khloe Aliapoh has the same item.

Cracked Anthocluster
Cracked Dendrocluster
Cracked Anthocrystal
Cracked Dendrocrystal

Of the 4 items listed above "Khloe Aliapoh" and "Silver Certificate of Commendation" have maps and flags.
No responded for the "Gold Certificate of Commendation" and "Bronze Certificate of Commendation"
It's hard when the same product is sold in different ways.😵‍💫

**Comment by github-1348A55** [comment]
I will close this thread for the time.
Thanks for developing and fixing this plugin!
