### ISSUE TITLE
Is it possible to add items from Commanders and such

### ISSUE THREAD

**Issue by ripsnortntear** [electr0sheep/ItemVendorLocation#4]
Things like Bombard Core and Sacred Spring Water are bought from vendors for Seals and Tomes. Is it possible to add these in so that we can know where to go for these technicality vendor items?

**Comment by electr0sheep** [comment]
In taking a quick look, I think this might be possible.
I think this is what I need for the GC seals items: https://github.com/xivapi/ffxiv-datamining/blob/master/csv/GCScripShopItem.csv

For the tomestones, it might be this: https://github.com/xivapi/ffxiv-datamining/blob/master/csv/SpecialShop.csv, but the format is a little different than I've seen before. That spreadsheet is the widest spreadsheet I've looked at, with hundreds of columns. It seems like there should be a SpecialShopItem spreadsheet, though, which there is not.

The bigger question is, the game itself readily tells you if you can purchase an item with gil, it just doesn't tell you where. I'm not sure there is an obvious prompt that would let you know an item can be purchased with gc seals or tomestones, so I may need to hook into the item's description to add an indicator it is purchasable with some form of currency.

**Comment by electr0sheep** [comment]
Actually, the ItemSearch plugin may have some useful things regarding special shops: https://github.com/Caraxi/ItemSearchPlugin/blob/master/ItemSearchPlugin/SpecialShopCustom.cs

I need to look at that plugin to see.

**Comment by electr0sheep** [comment]
My latest commits add this functionality. Gotta run through a few test cases to make sure everything mostly works, then I can submit the changes to the Dalamud repo.

**Comment by electr0sheep** [comment]
https://github.com/goatcorp/DalamudPlugins/pull/2039
