### ISSUE TITLE
Opening Plugin

### ISSUE THREAD

**Issue by Diamon81** [electr0sheep/ItemVendorLocation#44]
I am unable to get the drop down menu to extract when searching for vendor locations, the arrow button does not let me interact with it.  
![image](https://user-images.githubusercontent.com/128325861/226209296-080b9a7b-f08d-42d9-a1a8-220ea9b57a4e.png)

**Comment by electr0sheep** [comment]
You can either see if some small portion of that window is clickable, and try to drag it somewhere else.

If not https://goatcorp.github.io/faq/dalamud_troubleshooting.html#q-how-do-i-reset-dalamudplugin-window-locations

**Comment by Diamon81** [comment]
Thank you for the response I ended up reinstalling the game and it seesm to work I feel it was in the setting somewhere it was working on my laptop until I used a download UI from doing a backu on my desktop.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
