### ISSUE TITLE
[Bug] Missing Merchant & Vendor co-ordinates

### ISSUE THREAD

**Issue by Rueby** [electr0sheep/ItemVendorLocation#48]
Issue : Missing vendor coordinates, one is in lower limsa and one in an instanced (?) ocean fishing area. 

Dataset : Internal & Garland Tools
Items affected:
Ragworm
Krill
Plump Worm
Versatile Lure

Merchant & Mender in Limsa Lominsa Lower Decks (X: 3.2 - Y: 12.8)
Merchant & Mender in The Endeavor (X: 6.1 - Y: 6.1) 
(Source : https://ffxivteamcraft.com/db/en/item/29717/Versatile-Lure)

![image](https://user-images.githubusercontent.com/92205577/227129344-b1ab2ba5-a677-4586-9465-8dca4a641e2f.png)

**Comment by Rueby** [comment]
Hey I found something else, I'd rather not make another issue of it since it's related to this.

![image](https://user-images.githubusercontent.com/92205577/227631847-71fbc46e-c18b-49b5-9686-140879a4cb2f.png)

Affected NPC : Itinerant Moogle 
Dataset : Internal & Garland Tools
Items affected:
Everything the vendor has in its current and previous cycle
Actual NPC Location:
Limsa Lominsa Lower Decks ((X:9.4, Y:11.6)
New Gridania (X:12.4, Y:12.1)
Ul'dah - Steps of Nald (X:9.6, Y:9.1)

Source : https://ffxiv.consolegameswiki.com/wiki/Itinerant_Moogle

===========================================================================

![image](https://user-images.githubusercontent.com/92205577/227633039-e179b15c-c24b-4744-90e2-66934b247510.png)

Affected NPC : Hunt Billmaster (Maelstrom & Twin Adder) are missing from the list
Dataset : Internal & Garland Tools
Items Affected:
All items sold by the billmaster
Actual NPC Location:
Hunt Billmaster (Maelstrom) Limsa Lominsa Upper Decks (13.2,12.5)
Hunt Billmaster (Twin Adder) New Gridania (9.7,11.2)

Source (Maelstrom) : https://ffxiv.consolegameswiki.com/wiki/Hunt_Billmaster_(Maelstrom)
Source (Adders) : https://ffxiv.consolegameswiki.com/wiki/Hunt_Billmaster_(Twin_Adder)

===========================================================================

Thanks alot again, thought I'd throw these in here just in case.

**Comment by electr0sheep** [comment]
2f1c0ec55c696877e41b88358794b3dc794f03c5

**Comment by electr0sheep** [comment]
That commit should fix these issues. One thing I noticed, the itinerant moogles sell prisms for all kinds of currencies, but only the latest shows up. I actually don't think I care to look into this, as I would eat my lunch if anyone actually was really hoping for those stupid things and this would have helped them. 👅

**Comment by electr0sheep** [comment]
Forgot I was going to leave these issues open until I actually get stuff merged into the plugin repo ha
