### ISSUE TITLE
[Issue] Vendor Location appearing on chat tabs

### ISSUE THREAD

**Issue by imgidedin** [electr0sheep/ItemVendorLocation#49]
![image](https://user-images.githubusercontent.com/19570528/227302577-72d1aa1c-b78e-4745-b1e0-919d1b5beb6f.png)

Dont think they should be there xD

**Comment by Rueby** [comment]
[Issue#26](https://github.com/electr0sheep/ItemVendorLocation/issues/26) already covered that

**Comment by imgidedin** [comment]
Oh, ok, thanks, didnt saw that.
