### ISSUE TITLE
I can only seem to get this to work on the marketboard

### ISSUE THREAD

**Issue by HumblyMystic** [electr0sheep/ItemVendorLocation#6]
I can only seem to get this to work on the marketboard.
It does not work when selecting the item from your inventory

**Comment by electr0sheep** [comment]
Most likely this is related to this issue: https://github.com/electr0sheep/ItemVendorLocation/issues/2

You can confirm the issues are related by clicking on other items in the context menu to see if you can get the plugin to work when you click on the wrong thing.

It seems like plugins that modify the inventory context menu don't play well with each other. There is a fix for this on the way I think, but it might take a minute.

**Comment by HumblyMystic** [comment]
ah yes it is. I double checked a few different things and it does seem to be the issue. Thanks for the quick response
