### ISSUE TITLE
Weirdness with Zadnor vendor?

### ISSUE THREAD

**Issue by electr0sheep** [electr0sheep/ItemVendorLocation#64]
"Zadnor Riding Map" is listed as being sold by the Resistance Supplier vendor. I don't see any such thing in his list of items.

**Comment by GoblinGuide** [comment]
(It's actually sold by the Resistance Quartermaster, in case this helps track down the root cause.)

**Comment by Nukoooo** [comment]
This is actually a mistake on my code, fixed in PR#69

**Comment by electr0sheep** [comment]
Resistance Quartermaster is listed, but so is the Resistance Supplier

**Comment by electr0sheep** [comment]
The special shop 1770087 was being added for the Resistance Supplier as a hacky fix. It appears that is no longer necessary.

**Comment by electr0sheep** [comment]
Nuko removed this actually. I wonder why I still had it, maybe a bad git stash merge
