### ISSUE TITLE
All items from Island Sanctuary are missing

### ISSUE THREAD

**Issue by Uriei** [electr0sheep/ItemVendorLocation#66]
Hi, the Horrendous Hoarder from Island Sanctuary isn't referenced for any item in the plugin.

Example with Hi-Cordials:
![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/92f83a4a-8abc-44d9-b6b8-cef594c4e82b)
![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/8c24325f-4411-4279-aea5-fc0154d2df8f)

I'll add the stuff it sells:
- Purchase items with seafarer's cowries.
  - Exclusive wares.
    - Others
    ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/7ed6aa13-e500-44b1-8a0b-db51051f8442)
    ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/0a12d303-05ab-4b3f-ae7c-fc75f78d6b80)
  - Equipment and furnishings.
    - Armor
    ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/84b00f4c-dacd-47da-adcf-2bbfc41816b1)
    ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/8293ad96-bd0b-428d-badc-1715fc6c938a)
    - Others
    ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/b7174377-61a6-4085-9bb7-8dea73ce5b4c)
  - Materia and items.
    - Others
    ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/a4b552e1-c396-4402-8069-3b193c98ff02)
    ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/6dc2848f-8647-4122-a9e9-0ae3123f87f3)
- Purchase items with islander's cowries.
  - Others
  ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/e3a9d20d-3eee-4e6e-9a06-2a6c1b9f12d4)
  ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/24b59173-a865-452c-be11-a608d2ccde99)
  ![image](https://github.com/electr0sheep/ItemVendorLocation/assets/6078221/1798c964-7c54-4a79-b8bc-56b0b4a2a6ce)

**Comment by electr0sheep** [comment]
Thanks for the detailed report. I think the Island Sanctuary introduced an entirely new class of vendors that needs to have support added for.

**Comment by electr0sheep** [comment]
@Nukoooo It's not your fault. Did Island Sanctuary even exist when you did all that work? Anyway, I'm sure there will be other cases like this that arise.

I think I spent some time looking into this, but I don't think I was able to figure out how to include the island vendors. That was a while ago though, I haven't had much time to work on the plugin lately.

**Comment by electr0sheep** [comment]
Nuko fixed this
