### ISSUE TITLE
Being able to copy text

### ISSUE THREAD

**Issue by iv230** [electr0sheep/ItemVendorLocation#68]
Hi! What would be a nice enchancement is to be able to copy the text of a row, for instance if you want to share with someone who does not have the plugin or cannot find the item its vendor location, price, etc...

**Comment by electr0sheep** [comment]
That's not a bad idea. I think most of the work is already in place for this with the feature that prints vendors to the chat window. If I get some time, I'll work on this.

**Comment by Nukoooo** [comment]
Now you can copy the vendor info by right-clicking the button
![image](https://github.com/electr0sheep/ItemVendorLocation/assets/89713806/016cea96-4c81-4d32-acc0-4c3fc41e0606)
