### ISSUE TITLE
Maybe add a message when plugin has fully loaded?

### ISSUE THREAD

**Issue by electr0sheep** [electr0sheep/ItemVendorLocation#70]
I noticed that it can take a few moments for the plugin to initialize (on steam deck, for example). I wonder if it would be beneficial to add a message so that people know to wait if the context menu item isn't working. I was doing some testing on my steam deck after the latest update to make sure everything was working, and I was worried it was broken initially because of this. Granted, we're talking within like 5-20 seconds it was fully loaded, but still, I wonder if this catches people off guard?

**Comment by Nukoooo** [comment]
This is fixed in PR #72, the reason why it took so long to fully load the data is it keeps adding npcs that the plugin doesn't really need. I should have noticed that long time ago :P

**Comment by Nukoooo** [comment]
Closing as #72 is merged
