### ISSUE TITLE
Space in the Dalamud discord was having issues

### ISSUE THREAD

**Issue by electr0sheep** [electr0sheep/ItemVendorLocation#80]
They couldn't get the plugin to work. It may have something to do with Chat2. Attached is the log.
[dalamud.txt](https://github.com/electr0sheep/ItemVendorLocation/files/15502035/dalamud.txt)
https://discord.com/channels/581875019861328007/684745859497590843/1245653064568934461

**Comment by Nukoooo** [comment]
Fixed in 3071e77eeb09ff274cb2863929f9ffc98ec1c022, it was because the user is on free trial or doesn't purchase the expansion

**Comment by electr0sheep** [comment]
Space confirmed the fix is working, and that they are on free trial. Nuko, could you add me on discord? If you are willing to, my username is: electr0sheep
