### ISSUE TITLE
I think scrip color got messed up

### ISSUE THREAD

**Issue by electr0sheep** [electr0sheep/ItemVendorLocation#88]
Rroneek Horn Token is showing is purchasable with purple gatherers' scrips. They are purchasable with orange gatherers' scrips.

**Comment by Nukoooo** [comment]
Fixed by PR https://github.com/electr0sheep/ItemVendorLocation/pull/89. I should find a way to do it without manually updating it at some point, not sure if this is possible.

**Comment by Orphis** [comment]
I don't think we have anything in the data that would point to it. The 2/4/6/7 reward ids are a bit opaque.

**Comment by Nukoooo** [comment]
CurrencyManager in CS should help: https://github.com/aers/FFXIVClientStructs/blob/47dc5beefe9b5fb44bfb35edc768d866d322cb09/FFXIVClientStructs/FFXIV/Client/Game/CurrencyManager.cs#L10-L26C44
